x = float(input('Digite um número Real: '))
y = float(input('Digite outro numero Real: '))
z = float(input('Digite mais um número Real: '))
print('x = {0:1.3f}'.format(x))
print('y = {0:1.3f}'.format(y))
print('z = {0:1.3f}'.format(z))
print('x + y =', x + y)
print('x - y =', x - y)
print('y - x =', y - x)
print('x * y =', x * y)
print('x ** y =', x ** y)
print('y ** x =', y ** x)
print('x / y =', x / y)
print('y / x =', y / x)
print('x // y =', x // y)
print('y // x =', y // x)
print('x % y =', x % y)
print('y % x =', y % x)
print('='*23)
print('Olá, '*3, 'meu amigo.')
nome = input('Qual é o seu nome? ')
print('Segue abaixo algumas formatações com o input dado')
print('Olá, {0:s}!'.format(nome))
print('Olá, {0:20s}!'.format(nome))
print('Olá, {0:>20s}!'.format(nome))
print('Olá, {0:<20s}!'.format(nome))
print('Olá, {0:^20s}!'.format(nome))
#print('Olá, {0:=20s}!'.format(nome))
print('Olá, {0:=>20s}!'.format(nome))
print('Olá, {0:=<20s}!'.format(nome))
print('Olá, {0:=^20s}!'.format(nome))
print('Olá, {0:*^20s}!'.format(nome))
print('Olá, {0:a^20s}!'.format(nome))
print('Fuchique o código', end=' >>> ')
print('pra descobrir mais')
