entry = input('\nDigite algo:  ')
print(f'\nTipo = {type(entry)}')
#print(f'Is {entry} numeric? {entry.isascii()}')
print(f'Is {entry} printable? {entry.isprintable()}')
print(f'Is {entry} alpha num? {entry.isalnum()}')
print(f'Is {entry} digit? {entry.isdigit()}')
print(f'Is {entry} decimal? {entry.isdecimal()}')
print(f'Is {entry} numeric? {entry.isnumeric()}')
print(f'Is {entry} identifier? {entry.isidentifier()}')
print(f'Is {entry} space? {entry.isspace()}')
print(f'Is {entry} alphabetic? {entry.isalpha()}')
print(f'Is {entry} upper? {entry.isupper()}')
print(f'Is {entry} titled? {entry.istitle()}')
print(f'Is {entry} lower? {entry.islower()}') 
