print('Print normal')
print(r"print('Hello, friend!')")
print('Hello, friend!')
print('\nTAB entre palavras') 
print(r"print('Hello, \tfriend!')") 
print('Hello, \tfriend!')
print('\nQuebra de linhas')
print(r"print('Hello,\nfriend!')") 
print('Hello,\nfriend!')
print('\nJunção de linhas')
print(r"print('Hello, ', end='')") 
print(r"print('friend!')")
print('Hello, ', end='')
print('friend')
print('\nJunção de linhas com simbolos inclusos')
print(r"print('Hello, ', end='>>>')") 
print(r"print('friend!')")
print('Hello, ', end='>>>')
print('friend!\n')
print('Entre outros "escape characters" há:\n')
print(r"print('Contrabarra: \\')")
print('Contrabarra: \\ \n')
print(r"print('Aspas simples: \'')")
print('Aspas simples: \'\n') 
print(r'print("Aspas duplas: \"")')
print("Aspas duplas: \"\n") 
