print ('\nOLÁ MEU CARO!\n\nEscolha um número na sua mente entre 1 e 10.\n\nNão me fale ele, mantenha-o APENAS na sua mente.\n\nJá escolheu? Sim ou não?\n')
s_n = input ()
print ('\nSe escolheu, multiplique ele por 2.\n\nUse papel se você precisar.\n\nNão me diga o resultado, apenas sinalize quando você terminar\n')
mult = input ()
print ('\nPróximo passo, some 10 ao resultado da multiplicação.\n\nNão me fale o resultado.\n\nConseguiu fazer a conta, sim ou não?\n')
soma = input ()
print ('\nPenúltimo passo, divida o resultado obtido por 2.\n\nSinaliza pra mim quando você já terminar, sim ou não?\n')
div = input ()
print ('\nChegamos ao último passo.\n\nDo resultado obtido até agora, subtraia o número que vc pensou inicialmente.\n\nConseguiu?\n')
subt = input ()
print ('\nO resultado final da sua conta dá 5.\n\nMatemática é magica!')