algoritmo "sintaxeTimer"
//
var
   i : inteiro
inicio
   escreval("Iniciar contagem regressiva")
   timer(1500)
   timer(0)
   limpatela
   para i := 10 ate 1 passo -1 faca
      timer(0)
      limpatela
      timer(300)
      escreval(i)
   fimpara
   timer(0)
   limpatela
   escreval("/\/\/\/\/\/\/\/\/\/\/\/\/\")
   escreval("|                        |")
   escreval("|     Feliz ano novo     |")
   escreval("|                        |")
   escreval("\/\/\/\/\/\/\/\/\/\/\/\/\/")
fimalgoritmo