se (jogo = "S") ou (jogo = "s") entao
               vencedor := falso
               carta := "S"
               cartaJ := 0
               cartaB := 0
               totalJ := 0
               totalB := 0
            senao
               escreval("Placar final:")
               escreval("Jogador...["+numpcarac(placarJ)+"]")
               escreval("Banca.....["+numpcarac(placarB)+"]")
            fimse
